// <auto-generated />
using HACKATHON.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HACKATHON.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HACKATHON.Models.DegerTuru", b =>
                {
                    b.Property<int>("DegerTuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegerTuruAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegerTuruKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrupId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("VeriPeriyodu")
                        .HasColumnType("int");

                    b.HasKey("DegerTuruId");

                    b.HasIndex("GrupId");

                    b.ToTable("DegerTurleri");
                });

            modelBuilder.Entity("HACKATHON.Models.Grup", b =>
                {
                    b.Property<int>("GrupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrupAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.HasKey("GrupId");

                    b.HasIndex("KategoriId");

                    b.ToTable("Gruplar");
                });

            modelBuilder.Entity("HACKATHON.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategoriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("HACKATHON.Models.Sorumlu", b =>
                {
                    b.Property<int>("SorumluId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SorumluId");

                    b.ToTable("Sorumlular");
                });

            modelBuilder.Entity("HACKATHON.Models.SorumluAtama", b =>
                {
                    b.Property<int>("SorumluAtamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DegerTuruId")
                        .HasColumnType("int");

                    b.Property<int>("SorumluId")
                        .HasColumnType("int");

                    b.HasKey("SorumluAtamaId");

                    b.HasIndex("DegerTuruId");

                    b.HasIndex("SorumluId");

                    b.ToTable("SorumluAtamalari");
                });

            modelBuilder.Entity("HACKATHON.Models.VeriGirisi", b =>
                {
                    b.Property<int>("VeriGirisiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("Deger")
                        .HasColumnType("real");

                    b.Property<int>("DegerTuruId")
                        .HasColumnType("int");

                    b.Property<string>("Donem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VeriGirisiId");

                    b.HasIndex("DegerTuruId");

                    b.ToTable("VeriGirisleri");
                });

            modelBuilder.Entity("HACKATHON.Models.DegerTuru", b =>
                {
                    b.HasOne("HACKATHON.Models.Grup", "Grup")
                        .WithMany("DegerTurleri")
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grup");
                });

            modelBuilder.Entity("HACKATHON.Models.Grup", b =>
                {
                    b.HasOne("HACKATHON.Models.Kategori", "Kategori")
                        .WithMany("Gruplar")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("HACKATHON.Models.SorumluAtama", b =>
                {
                    b.HasOne("HACKATHON.Models.DegerTuru", "DegerTuru")
                        .WithMany("SorumluAtamalari")
                        .HasForeignKey("DegerTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HACKATHON.Models.Sorumlu", "Sorumlu")
                        .WithMany("SorumluAtamalari")
                        .HasForeignKey("SorumluId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DegerTuru");

                    b.Navigation("Sorumlu");
                });

            modelBuilder.Entity("HACKATHON.Models.VeriGirisi", b =>
                {
                    b.HasOne("HACKATHON.Models.DegerTuru", "DegerTuru")
                        .WithMany("VeriGirisleri")
                        .HasForeignKey("DegerTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DegerTuru");
                });

            modelBuilder.Entity("HACKATHON.Models.DegerTuru", b =>
                {
                    b.Navigation("SorumluAtamalari");

                    b.Navigation("VeriGirisleri");
                });

            modelBuilder.Entity("HACKATHON.Models.Grup", b =>
                {
                    b.Navigation("DegerTurleri");
                });

            modelBuilder.Entity("HACKATHON.Models.Kategori", b =>
                {
                    b.Navigation("Gruplar");
                });

            modelBuilder.Entity("HACKATHON.Models.Sorumlu", b =>
                {
                    b.Navigation("SorumluAtamalari");
                });
#pragma warning restore 612, 618
        }
    }
}
